### ISSUE TITLE
Reboots on incoming phonecall

### ISSUE THREAD

**Issue by robbat2** [CyanogenMod/android_device_lge_bullhead#7]
Updates to nightly 20151123 and now my device spontaneously reboots whenever I get an incoming phone call :-(.

Unsure how best to aid your debugging; not sure if there is anything in the logs (point me to which ones you might want, I can check).

**Comment by PsychoI3oy** [comment]
update to 20160324-5, this was fixed yesterday morning

**Comment by robbat2** [comment]
Confirmed fixed on 20160325, but now camera isn't working; will open a new issue
